#!/usr/bin/env bash

# This individual file is necessary because stream_to_tmp_file expects
# a data stream, so, since it is not possible to send it from within the script
# it is necessary to have this script that calls the test function with a pipe.


testData="$BIOBASH_HOME/testdata/simpleString.txt"
cat  $testData | ./test_stream_to_tmp_file
