#!/usr/bin/env bash
# Assumes bashrc has been sourced!!
#

source $SHML_LIB

#Header
echo ""

echo "$(hr '- ' 20)"
echo $(attribute bold)$(fgcolor black "  BIOBASH STANDARD TEST ") $(fgcolor end)$(attribute end)
date
echo "$(hr '- ' 20)"



#--------------------------------------------------------------------
#    BB::IO TESTS
#--------------------------------------------------------------------
echo ""
echo $(fgcolor blue " Running BB::IO tests.") $(fgcolor end)
./run_test_get_data_stream
./run_test_stream_to_tmp_file


#--------------------------------------------------------------------
#   BB::FILE TESTS
#--------------------------------------------------------------------
echo ""
echo $(fgcolor blue " Running BB::File tests.") $(fgcolor end)
./test_file_is_fasta
./test_file_is_fastq
./test_file_is_multiple
./test_file_fastq_to_fasta
./test_file_multiple_fasta_to_singles
./test_file_uncompress
./test_file_get_assembly_consensus

#--------------------------------------------------------------------
#   BB::SEQ TESTS
#--------------------------------------------------------------------
echo ""
echo $(fgcolor blue " Running BB::Seq tests.") $(fgcolor end)
./test_seq_get_fasta_components
./test_seq_get_fastq_quality

#--------------------------------------------------------------------
#   BB::INDEX TESTS
#--------------------------------------------------------------------
echo ""
echo $(fgcolor blue " Running BB::Index tests.") $(fgcolor end)
./test_index_genome_indexing


#--------------------------------------------------------------------
#       BB::ALIGN TESTS
#--------------------------------------------------------------------
echo ""
echo $(fgcolor blue " Running BB::align tests.") $(fgcolor end)
./test_align_map_reads_to_genome


#--------------------------------------------------------------------
#       BB::FORMAT TESTS
#--------------------------------------------------------------------
echo ""
echo $(fgcolor blue " Running BB::format tests.") $(fgcolor end)
./test_format_sam_to_bam
./test_format_fastq_to_fasta


#--------------------------------------------------------------------
#       UTILITY TESTS
#--------------------------------------------------------------------
echo ""
echo $(fgcolor blue " Running Utility tests.") $(fgcolor end)
./test_utility_os_default_number_of_cores


#Some output formatting
echo ""
