#!/usr/bin/env bash

# This individual file is necessary because get_data_stream expects
# a data stream, so, since it is not possible to send it from within the script
# it is necessary to have this script that calls the test function with a pipe.


testData="$BIOBASH_HOME/testdata/simpleString.txt"
cat  $testData | ./test_io_get_data_stream

# This is a way to make it fail, call the function without input:
#./test_io_get_data_stream


