#!/usr/bin/env bash
# Assumes bashrc has been sourced!!
#

source $SHML_LIB

echo ""

echo "$(hr '- ' 20)"
echo $(attribute bold)$(fgcolor black "  BIOBASH STANDARD TEST ") $(fgcolor end)$(attribute end)
date
echo "$(hr '- ' 20)"
echo ""

echo $(fgcolor blue " Running BB::IO tests.") $(fgcolor end)
./run_test_get_data_stream
./run_test_stream_to_tmp_file

echo ""
echo $(fgcolor blue " Running BB::File tests.") $(fgcolor end)
./test_file_is_fasta
./test_file_is_fastq
./test_file_is_multiple
./test_file_fastq_to_fasta
./test_file_multiple_fasta_to_singles
./test_file_uncompress

echo ""
echo $(fgcolor blue " Running BB::Seq tests.") $(fgcolor end)
./test_seq_get_fasta_components

echo ""
