#!/usr/bin/env bash

#Tests  BBalign::run_blast

# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBalign.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

query="$BIOBASH_HOME/testdata/hepatitis_virus_raw_reads.fq.gz"
target="some_db"


#Arrange.
expected="SO:unsorted"

# Act
# Create a temporary directory to hold results
#dir=$(file::make_temp_dir "BB_" "false")
#samFile="${dir}/bbsam.sam"

#BBalign::map_reads_to_genome --input "${testData}" -x $BIOBASH_HOME/testdata/ --jobs 2 -o ${samFile}

BBalign::run_blast --input ${query} -d ${target} --header
exit 0
result=$(head -n 1 "${samFile}" | awk '{print $3}')




#Assert
unit_test_header
unit_test_spacer $(echo -n "${0}")  $(eval_outcome "${result}" "${expected}")
unit_test_footer