#!/usr/bin/env bash

#Tests  BBfile::format_sam_to_bam

# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBformat.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

testData="${BIOBASH_HOME}/testdata/small.sam"
#testData="/Users/andres/Dev/repo/sandbox/sam2bam/bbsam.sam"


#Arrange.
# This expected number is based on the option "-k" of the command "du":
# Display block counts in 1024-byte (1 kiB) blocks.
# This option was settled after seeing that the inspection of BAM files either using
# zcat, gzcat or gunzip -c, behave differently in OSX and Linux, under the same BASH version.
expected="4"

# Act
# Create a temporary directory to hold results
dir=$(file::make_temp_dir "BB_" "false")
bamFile="${dir}/output.bam"

BBformat::sam_to_bam --input "${testData}" -o ${bamFile}




# This result option is DEPRECATED and maintained here only for informative porpouses.
# given that zcat, gzcat or gunzip -c, behave differently in OSX and Linux, under the same BASH version.
# result=$(gunzip -c ${bamFile} | head -n 2 | awk '{print $3}' | sed -E '/^[[:blank:]]*$/d')
result=$(du -k ${bamFile} | awk '{print $1}')

#Assert
unit_test_header
unit_test_spacer $(echo -n "${0}")  $(eval_outcome "${result}" "${expected}")
unit_test_footer