#!/usr/bin/env bash

#Tests  BBfile::fastq_to_fasta


# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBfile.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source $BASHUTILITY_LIB_PATH/file.sh;
source ./unit_testing_common.sh


testData="$BIOBASH_HOME/testdata/example.fastq"

#Arrange
expected=">ee15a423-b008-44be-a4b2-5441d11b0b94"

# Note that we created this empty temporary file only to get the name...
outFile=$(file::make_temp_file)

#Because we are going to use it to create another one with th .gz extension
outFileGZ="$outFile.gz"

#Act
result=$(BBfile::fastq_to_fasta -i $testData  --output $outFileGZ)
echo $result

# OSX has an issue with zcat, it always complains because can't find the file...
# But "gunzip -c" appears to have the same effect and works both in Linux and OSX.
# Check this: https://serverfault.com/questions/570024/zcat-gzcat-works-in-linux-not-on-osx-general-linux-osx-compatibility
result2=$(gunzip -c  $outFile | head -n 1 | awk '{print $1}')


#Assert
unit_test_header

eval_outcome "$result2" "$expected"

unit_test_footer