#!/usr/bin/env bash

#Tests  BBSeq::get_fasta_components


# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBseq.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source $BASHUTILITY_LIB_PATH/file.sh;
source ./unit_testing_common.sh


testData="$BIOBASH_HOME/testdata/apoe_mul.fasta"

# Capture arguments as a string. Necessary when created a script that calls this function
# myArgs="printf ${@}"

#Arrange
expected="KY560197.1-4"

#Act
result=$(BBSeq::get_fasta_components --input $testData -d | tail -n 1)

#Assert
unit_test_header
eval_outcome "$result" "$expected"
unit_test_footer

