#!/usr/bin/env bash

#Tests  BBfile::is_fasta
# This script is called and receives a data stream, then outputs it.

# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBdb.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source $BASHUTILITY_LIB_PATH/string.sh;
source ./unit_testing_common.sh

testData="$BIOBASH_HOME/testdata/apoe_mul.fasta"



#Arrange.
# Number of files created inside the directory
expected=11

# Act
# Create a temporary directory to hold results
name=$(string::random)
BBdb::make_blast_db -i "${testData}" --rename "my blast database"  -o ${name}  -t N > /dev/null 2>&1



result=$(ls -l ${name} | wc -l | awk '{print $1}')


#Assert
unit_test_header
unit_test_spacer $(echo -n "${0}")  $(eval_outcome "${result}" "${expected}")
unit_test_footer

#Clean up 
rm -Rf "${name}"