#!/usr/bin/env bash

#Tests  utility-os::default_number_of_cores


# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BASHUTILITY_LIB_PATH/os.sh;
source ./unit_testing_common.sh

#Arrange
expected=$(echo "${BIOBASH_CORES}/2" | bc)
#echo $expected

#Act
result=$(os::default_number_of_cores)
#echo $result

#Assert
unit_test_header
unit_test_spacer $(echo -n "${0}")  $(eval_outcome "${result}" "${expected}")
unit_test_footer