#!/usr/bin/env bash

#Tests  BBfile::is_multiple_fasta
# This script is called and receives a data stream, then outputs it.

# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBfile.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

#This file contains the string: "AGCT"
testData="$BIOBASH_HOME/testdata/apoe_mul.fasta"

#Arrange
expected=0 #is multiple fasta

#Act
result=$(BBfile::is_multiple_fasta $testData)

#Assert
unit_test_header

eval_outcome "$result" "$expected"   

unit_test_footer