#!/usr/bin/env bash

#Tests  BBfile::format_sam_to_bam

# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBformat.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

testData="${BIOBASH_HOME}/testdata/toy.sam"
#testData="/Users/andres/Dev/repo/sandbox/sam2bam/bbsam.sam"


#Arrange.
#This expected is for bbsam.bam which is NOT in the testdata directory given its size.
#expected="SO:unsorted"
expected="LN:40"

# Act
# Create a temporary directory to hold results
dir=$(file::make_temp_dir "BB_" "false")
bamFile="${dir}/output.bam"

BBformat::sam_to_bam --input "${testData}" -o ${bamFile}




# This result is for the bbsam.sam file.
#result=$(head -n 1 "${testData}" | awk '{print $3}')

result=$(gzcat ${bamFile} | head -n 2 | awk '{print $3}' | sed -E '/^[[:blank:]]*$/d')


#Assert
unit_test_header
unit_test_spacer $(echo -n "${0}")  $(eval_outcome "${result}" "${expected}")
unit_test_footer