#!/usr/bin/env bash

#Tests  BBfile::is_fastq


# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBfile.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

#This file contains the string: "AGCT"
testData="$BIOBASH_HOME/testdata/example.fastq"

#Arrange
expected=0 #is fastq

#Act
result=$(BBfile::is_fastq $testData)

#Assert
unit_test_header

eval_outcome "$result" "$expected"   

unit_test_footer