#!/usr/bin/env bash

#Tests  BBfile::is_fasta
# This script is called and receives a data stream, then outputs it.

# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBalign.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

testData="$BIOBASH_HOME/testdata/hepatitis_virus_raw_reads1.fq.gz,$BIOBASH_HOME/testdata/hepatitis_virus_raw_reads2.fq.gz"
#testData="$BIOBASH_HOME/testdata/hepatitis_virus_raw_reads.fq.gz"


#Arrange.
expected="SO:unsorted"

# Act
# Create a temporary directory to hold results
dir=$(file::make_temp_dir "BB_" "false")
samFile="${dir}/bbsam.sam"

BBalign::map_reads_to_genome --input "${testData}" -x $BIOBASH_HOME/testdata/ --jobs 2 -o ${samFile}


result=$(head -n 1 "${samFile}" | awk '{print $3}')



#Assert
unit_test_header
unit_test_spacer $(echo -n "${0}")  $(eval_outcome "${result}" "${expected}")
unit_test_footer