#!/usr/bin/env bash

#Tests  BBfile::is_multiple_fasta


# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBfile.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

#This file contains the string: "AGCT"
testData="$BIOBASH_HOME/testdata/wholegenome.fasta"

#Arrange
expected=0 #is multiple fasta

#Act
#result=$(BBfile::is_multiple_fasta --input $testData)
result=$(cat "${testData}" | BBfile::is_multiple_fasta)

#Assert
unit_test_header
eval_outcome "$result" "$expected"   
unit_test_footer