#!/usr/bin/env bash

#Tests  BBfile::is_fasta
# This script is called and receives a data stream, then outputs it.

# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBindex.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source ./unit_testing_common.sh

testData="$BIOBASH_HOME/testdata/hepatitis_delta_virus.fa"

#Arrange
expected=1679

#Act
# Create a temporary directory to hold results
dir=$(file::make_temp_dir "BB_" "false")

$(BBindex::genome_indexing -i $testData --jobs 2 --output "${dir}")

result=$(tail -n 1 ${dir}/ref/genome/1/info.txt | awk '{print $5}')

#Assert
unit_test_header
unit_test_spacer $(echo -n "${0}")  $(eval_outcome "${result}" "${expected}")
unit_test_footer