#!/usr/bin/env bash

#Tests  BBfile::fastq_to_fasta


# shellcheck source=/dev/null # to ignore the errorbash-language-server
source $BIOBASH_NATIVE_LIB_PATH/BBfile.sh
source $BASHUTILITY_LIB_PATH/feedback.sh;
source $BASHUTILITY_LIB_PATH/file.sh;
source ./unit_testing_common.sh


testData="$BIOBASH_HOME/testdata/apoe_mul.fasta.gz"

#Arrange
outDir=$(file::make_temp_dir BB false)
echo $outDir
expected="NNNNNNNNNNNNNNNNNNNN"


#Act
result=$(BBfile::multiple_fasta_to_singles "$testData"  "$outDir")
result2=$(gunzip -c "${outDir}"/apoe_mul.part_KY560197.1-4.fasta.gz  | tail -n 1)


#Assert
unit_test_header

eval_outcome "$result2" "$expected"

unit_test_footer