site_name: BioBASH
nav:
    - Home: index.md
    - Alignment: BBalign.md
    - Annotation: BBannotation.md
    - Databases: BBdb.md
    - File: BBfile.md
    - Graphics: BBgraphics.md
    - Indexing: BBindex.md
    - Lists: BBList.md
    - Sequence: BBseq.md
    - Variation: BBvariation.md
theme: readthedocs
