#!/usr/bin/env bash
source ./process_optargs
echo "hola"


function myfunction () {    # The function whose options/args we want to process

 # Initialise the necessary variables that will be checked / populated by process_optargs
   local -A OPTIONS=()
   local -a ARGS=()
   local -a VALID_FLAG_OPTIONS=( -p/--processors )    # note -v and --version represent separate flags here! (e.g. '-v' could be for 'verbose')
   local -a VALID_KEYVAL_OPTIONS=( -i/--input )
   local COMMAND_NAME="myfunction"

 # Perform the processing to populate the OPTIONS and ARGS arrays.
process_optargs "$@" || exit 1


# echo "${OPTIONS[@]}"
for i in "${OPTIONS[@]}";do
    echo "${OPTIONS[@]}"
done


 # Validate parsed options and arguments
   if is_in '-h' "${!OPTIONS[@]}" || is_in '--help' "${!OPTIONS[@]}"
   then echo "MOSTRAR AYUDA"
   fi

   if   is_in '-r'            "${!OPTIONS[@]}"; then REPS="${OPTIONS[-r]}"
   elif is_in '--repetitions' "${!OPTIONS[@]}"; then REPS="${OPTIONS[--repetitions]}"
   fi

   if   test "${#ARGS[@]}" -lt 2
   then error "myfunction requires at least 2 non-option arguments"
        exit 1
   fi

   # ...etc
}


echo "REPS:" $REPS

myfunction -i