#!/usr/bin/env bash
source $BIOBASH_LIB/process_optargs.sh;
source $BASHUTILITY_LIB_PATH/feedback.sh;
source $BASHUTILITY_LIB_PATH/file.sh;


function myfunction () {    # The function whose options/args we want to process

# Initialise the necessary variables that will be checked / populated by process_optargs
  local -A OPTIONS=()
  local -a ARGS=()
  local -a VALID_FLAG_OPTIONS=( -h/--header -s/--sequence -d/--id )
  local -a VALID_KEYVAL_OPTIONS=( -i/--input )
  local COMMAND_NAME="myfunction"

# Perform the processing to populate the OPTIONS and ARGS arrays.
process_optargs "$@" || exit 1

# Validate parsed options and arguments

  # Check input file (REQUIERED!)
  if   is_in '-i'      "${!OPTIONS[@]}"; then file="${OPTIONS[-i]}"
  elif is_in '--input' "${!OPTIONS[@]}"; then file="${OPTIONS[--input]}"
  else
    echo "INPUT FILE REQUIRED"
    exit
  
  fi

  #Show header
  if is_in '-h' "${!OPTIONS[@]}" || is_in '--header' "${!OPTIONS[@]}"
    then echo "MOSTRAR HEADER"
  fi
  #Show sequence
  if is_in '-s' "${!OPTIONS[@]}" || is_in '--sequence' "${!OPTIONS[@]}"
    then echo "MOSTRAR SECUENCIA"
  fi
  #Show sequence ID
  if is_in '-d' "${!OPTIONS[@]}" || is_in '--id' "${!OPTIONS[@]}"
    then echo "MOSTRAR ID"
  fi

echo "Iterando sobre el array de opciones:"
for i in "${OPTIONS[@]}";do
    echo "${!OPTIONS[@]} - ${i}"
done

echo "-- Opciones tomadas --"
echo "${!OPTIONS[@]}"

}
#Capture arguments as a string
myArgs="printf ${@}"

#Send to function
myfunction ${myArgs}


